---
- name: Figuring out the server architecture
  shell: uname -m
  register: rawarch

- name: Setup and initialize variables
  set_fact:
    current_host: "{{ hostvars[inventory_hostname].inter_name }}"
    fabricworkdir: "/opt/gopath/{{ env }}/fabric"
    gopath: "/opt/gopath/{{ env }}"
    arch: "{{ rawarch.stdout}}"
    peers: "{{ [] }}"
    orderers: "{{ [] }}"
    cas: "{{ [] }}"
    cakeys: "{{ {} }}"
    adminkeys: "{{ {} }}"
    kafkas: "{{ [] }}"
    kafkanodes: ""
    zookeepers: "{{ [] }}"
    znodes: ""
    zkparam: ""
    index: 1
    zoo_ids: "{{ {} }}"
    kafka_ids: "{{ {} }}"
    zookeeperls: "{{ [] }}"
    kafkals: "{{ [] }}"
    peerls: "{{ [] }}"
    ordererls: "{{ [] }}"
    cals: "{{ [] }}"
    allpeers: "{{ [] }}"
    clihost: ""
    filterstr: ""
    thetag: "{{ rawarch.stdout + '-' + fabric.tag }}"
    baseimagetag: "{{ rawarch.stdout + '-' + fabric.baseimage_tag }}"
    catag: "{{ rawarch.stdout + '-' + fabric.ca.tag }}"

- set_fact:
    server: "{{ fabric.network[current_host].server | default([]) }}"

- name: Make sure that working directory is clean
  become: true
  file:
    path: "{{ fabricworkdir }}/run"
    state: "absent"

- name: Make sure that working directory is clean
  file:
    path: "{{ fabricworkdir }}/run"
    state: "directory"

- name: Create component list
  set_fact:
    cals: "{{ cals | default([]) + item.value.cas | default([]) }}"
    ordererls: "{{ ordererls | default([]) + item.value.orderers | default([]) }}"
    peerls: "{{ peerls | default([]) + item.value.peers | default([]) }}"
    zookeeperls: "{{ zookeeperls | default([]) + item.value.zookeepers | default([]) }}"
    kafkals: "{{ kafkals | default([]) + item.value.kafkas | default([]) }}"
  with_dict: "{{ fabric.network }}"

- name: Sort component list
  set_fact:
    zookeeperls: "{{ zookeeperls | sort }}"
    kafkals: "{{ kafkals | sort }}"

- name: Generate zookeeper node list
  set_fact:
    znodes: "{{ znodes }} server.{{ index }}={{ item }}:2888:3888"
    zkparam: "{{ zkparam + item }}:2181 "
    zoo_ids: "{{ zoo_ids | combine({item: index}) }}"
    index: "{{ index | int + 1 }}"
  with_items: "{{ zookeeperls | default([]) }}"

- name: Reset the index
  set_fact:
    index: 1

- name: Generate kafka broker ids
  set_fact:
    kafka_ids: "{{ kafka_ids | combine({item: index}) }}"
    index: "{{ index | int + 1 }}"
  with_items: "{{ kafkals | default([]) }}"

- name: Get all peer object list
  set_fact:
    allpeers: |
      {{ allpeers | default([]) + [{'org':item.split('@')[1].split('.')[-1],
        'hostname':item.split('@')[1].split('.')[0],
        'name':item.split('@')[1],
        'role':item.split('@')[0]}] }}
  with_items: "{{ peerls }}"

- name: Get all ca object list
  set_fact:
    allcas: |
      {{ allcas | default([]) + [{ 'org':item.split('.')[-1],
        'name':item }] }}
  with_items: "{{ cals }}"

- name: Get all orderer object list
  set_fact:
    allorderers: |
      {{ allorderers | default([]) + [{ 'org':item.split('.')[-1],
        'name':item }] }}
  with_items: "{{ ordererls }}"

- name: Get peer container list
  set_fact:
    peers: |
      {{ peers + [{'org':item.split('@')[1].split('.')[-1],
        'name':item.split('@')[1],
        'role':item.split('@')[0]}] }}
  with_items: "{{ fabric.network[current_host].peers | default([]) }}"

- name: Get ca container list
  set_fact:
    cas: |
      {{ cas + [{'org':item.split('.')[-1],
        'name':item }] }}
  with_items: "{{ fabric.network[current_host].cas | default([]) }}"

- name: Get orderer container list
  set_fact:
    orderers: |
      {{ orderers + [{'org':item.split('.')[-1],
        'name':item }] }}
  with_items: "{{ fabric.network[current_host].orderers | default([]) }}"

- name: Set zookeeper and kafka container list
  set_fact:
    zookeepers: "{{ fabric.network[current_host].zookeepers | default([]) }}"
    kafkas: "{{ fabric.network[current_host].kafkas | default([]) }}"

- name: Pull certificates from the builder machine
  command: >-
    scp -i "/opt/gopath/id_rsa" -r -o "StrictHostKeyChecking no" "{{ fabric.
    ssh_user }}@{{ hostvars[groups['builders'][0]].private_ip }}:{{ fabricworkdir }}/certs.tgz"
    "{{ fabricworkdir }}/allcerts.tgz"

- name: Pull container images from the builder machine
  command: >-
    scp -i "/opt/gopath/id_rsa" -r -o "StrictHostKeyChecking no" "{{ fabric.
    ssh_user }}@{{ hostvars[groups['builders'][0]].private_ip }}:{{ fabricworkdir }}/images/fabricimages.tar"
    "{{ fabricworkdir }}/fabricimages.tar"
  when: fabric.tag == '' and inventory_hostname not in groups['builders']

- name: Pull container version file from the build machine
  command: >-
    scp -i "/opt/gopath/id_rsa" -r -o "StrictHostKeyChecking no" "{{ fabric.
    ssh_user }}@{{ hostvars[groups['builders'][0]].private_ip }}:{{ fabricworkdir }}/images/VERSION"
    "{{ fabricworkdir }}/VERSION"
  when: fabric.tag == ''

- name: Load all the docker images created by build machine
  shell: >-
    docker load -i {{ fabricworkdir }}/fabricimages.tar
  when: fabric.tag == '' and inventory_hostname not in groups['builders']

- name: Find out the image tags
  slurp:
    src: "{{ fabricworkdir }}/VERSION"
  register: project_version
  when: fabric.tag == ''

- name: Set the container tag
  set_fact:
    thetag: "{{ arch + '-' + (project_version['content'] | b64decode) }}"
  when: fabric.tag == ''

- name: Unpack the certificates
  unarchive:
    src: "{{ fabricworkdir }}/allcerts.tgz"
    dest: "{{ fabricworkdir }}/run"
    remote_src: true

- name: Process private key files
  find:
    paths: "{{ fabricworkdir }}/run/keyfiles/{{ item[0].org }}/{{ item[1] }}"
    patterns: "*_sk"
    recurse: yes
  with_nested:
    - "{{ cas }}"
    - ["ca", "tlsca"]
  when: cas | length > 0
  register: privatekeys

- name: Process admin key files
  find:
    paths: "{{ fabricworkdir }}/run/keyfiles/{{ item.org }}/users/Admin@{{ item.org }}/msp/keystore"
    patterns: "*_sk"
    recurse: yes
  with_items:
    - "{{ allcas }}"
  when: server | length > 1
  register: adminprocesskeys

- name: Process private key files
  template:
    src: "{{ playbook_dir }}/../deploy_compose/fabricsetup/templates/fabric-ca-server-config.j2"
    dest: "{{ fabricworkdir }}/run/keyfiles/{{ item.org }}/ca/fabric-ca-server-config.yaml"
  with_items: "{{ cas }}"

- name: Setup ca private key values
  set_fact:
    cakeys: |
      {{ cakeys | combine( {item.item[0].org+'_'+item.item[1]: item.files[0].path.split('/')[-1] } ) }}
  with_items: "{{ privatekeys.results }}"
  no_log: True

- name: Setup admin private key values
  set_fact:
    adminkeys: |
      {{ adminkeys | combine( {item.item.org: item.files[0].path.split('/')[-1] } ) }}
  with_items: "{{ adminprocesskeys.results }}"
  when: server | length > 1
  no_log: True

- name: Get the peer org list
  set_fact:
    peerorgs: "{{ peers | map(attribute='org') | list  | unique | sort }}"

- name: Get all peer orgs
  set_fact:
    orgmembers: "{{ peers | map(attribute='org') | list  | unique | sort | join(\".member' '\") | trim | replace(' ', ',') }}"

- name: Pull container images from the docker hub
  command: "docker pull {{ item }}"
  when: fabric.tag | length > 0
  with_items:
    - "hyperledger/fabric-tools:{{ thetag }}"
    - "hyperledger/fabric-ccenv:{{ thetag }}"
    - "hyperledger/fabric-kafka:{{ thetag }}"
    - "hyperledger/fabric-zookeeper:{{ thetag }}"
    - "hyperledger/fabric-peer:{{ thetag }}"
    - "hyperledger/fabric-orderer:{{ thetag }}"
    - "hyperledger/fabric-couchdb:{{ thetag }}"
    - "hyperledger/fabric-baseimage:{{ baseimagetag }}"
    - "hyperledger/fabric-baseos:{{ baseimagetag }}"
    - "node:8.9"

- name: Create docker compose files
  template:
    src: "{{ playbook_dir }}/fabricsetup/templates/{{ item.name }}.j2"
    dest: "{{ fabricworkdir }}/run/{{ item.name }}.yml"
  when: item.flag | length > 0
  with_items:
    - { name: "ca-compose", flag: "{{ cas }}" }
    - { name: "zookeeper-compose", flag: "{{ zookeepers }}" }
    - { name: "kafka-compose", flag: "{{ kafkas }}" }
    - { name: "orderer-compose", flag: "{{ orderers }}" }
    - { name: "peer-compose", flag: "{{ peers }}" }
    - { name: "server-compose", flag: "{{ server }}" }

- name: Start fabric components
  command: "docker-compose -p {{ env }}.{{ item.name }} -f {{ fabricworkdir }}/run/{{ item.name }}.yml up -d"
  when: item.flag | length > 0
  with_items:
    - { name: "ca-compose", flag: "{{ cas }}" }
    - { name: "zookeeper-compose", flag: "{{ zookeepers }}" }
    - { name: "kafka-compose", flag: "{{ kafkas }}" }
    - { name: "orderer-compose", flag: "{{ orderers }}" }
    - { name: "peer-compose", flag: "{{ peers }}" }
  tags: "fabricup"
#####################################################################

- name: Locate a host to run peer channel create command
  set_fact:
    clihost: "{{ item }}"
    clipeer: "{{ allpeers | random }}"
    cliorderer: "{{ allorderers | random }}"
  when: peers | length > 0 and clihost == ""
  with_items: "{{ groups['allnodes'] }}"
###
- name: Copy Dockerfile-server file and app and configs directory to server hosts
  synchronize:
    src: "{{ playbook_dir }}/fabricsetup/files/{{ item }}"
    dest: "{{ fabricworkdir }}/run"
  with_items:
    - app
    - configs
    - Dockerfile-server
  no_log: True
  when: server | length > 1

- name: Template testAPI
  vars:
    CHANNEL_NAME: "{{ fabric.channel_name }}"
  template:
    src: "{{ playbook_dir }}/fabricsetup/templates/testAPI.sh.j2"
    dest: "{{ fabricworkdir }}/run/app/testAPI.sh"
  when: server | length > 1

- name: Template config.js
  template:
    src: "{{ playbook_dir }}/fabricsetup/templates/config.js.j2"
    dest: "{{ fabricworkdir }}/run/app/config.js"
  when: server | length > 1

- name: Template config.json
  template:
    src: "{{ playbook_dir }}/fabricsetup/templates/config.json.j2"
    dest: "{{ fabricworkdir }}/run/configs/config.json"
  when: server | length > 1  

- name: Template network-config
  vars:
    keyfilesdir: /etc/hyperledger/allorgs
  template:
    src: "{{ playbook_dir }}/fabricsetup/templates/network-config.j2"
    dest: "{{ fabricworkdir }}/run/configs/network-config.yml"
  when: server | length > 1

- name: Template org configs
  template:
    src: "{{ playbook_dir }}/fabricsetup/templates/org-config.j2"
    dest: "{{ fabricworkdir }}/run/configs/{{ item }}-config.yml"
  when: server | length > 1
  with_items: "{{ peerorgs }}"

###
- name: Make sure that chaincode directory exists
  file:
    path: "{{ fabricworkdir }}/run/keyfiles/chaincode"
    state: "directory"
    mode: 0775
  when: clihost == inventory_hostname #TODO

- name: Move chaincode to the server
  copy:
    src: "{{ playbook_dir }}/fabricsetup/templates/example_cc.go"
    dest: "{{ fabricworkdir }}/run/keyfiles/chaincode/example_cc.go"
    mode: "u=rw,g=rw"
  when: clihost == inventory_hostname #TODO
###

- name: Start the server container
  become: true
  docker_service:
    project_src: "{{ fabricworkdir }}/run"
    project_name: "{{ env }}.server-compose"
    files: 
      - server-compose.yml
    state: present
  when: server | length > 1

- wait_for:
    host: "{{ server }}"
    port: 4000
  when: server | length > 1

- name: Run testAPI.sh
  shell: 'docker exec {{ server }} bash -c "./testAPI.sh -l node"'
  async: 150
  poll: 0
  when: server | length > 1
  



#################################################

# - name: Make sure that working directory exists and clean
#   file:
#     path: "{{ fabricworkdir }}/run/keyfiles/chaincode"
#     state: "directory"
#     mode: 0775
#   when: clihost == inventory_hostname

# - name: Move chaincode to the server
#   copy:
#     src: "{{ playbook_dir }}/fabricsetup/templates/firstcode.go"
#     dest: "{{ fabricworkdir }}/run/keyfiles/chaincode/firstcode.go"
#     mode: "u=rw,g=rw"
#   when: clihost == inventory_hostname

# - name: Create peer channel command script
#   template:
#     src: "{{ playbook_dir }}/fabricsetup/templates/dochannel.j2"
#     dest: "{{ fabricworkdir }}/run/keyfiles/dochannel.sh"
#     mode: "u=rx,g=rx"
#   when: clihost == inventory_hostname

# - name: Create peer channel command docker compose file
#   template:
#     src: "{{ playbook_dir }}/fabricsetup/templates/cli-compose.j2"
#     dest: "{{ fabricworkdir }}/run/cli-compose.yml"
#   when: clihost == inventory_hostname

# - name: Wait for containers to be ready
#   pause:
#     seconds: 30

# - name: Start fabriccli components
#   command: "docker-compose -p {{ env }}.cli -f {{ fabricworkdir }}/run/cli-compose.yml up -d"
#   when: clihost == inventory_hostname
