---
- name: Try to get the project version from the baseimage_tag
  set_fact:
    project_version: >-
      {{ fabric.helper_tag |
         regex_replace('.*([0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}).*', '\1') }}
    baseimage_tag: "{{ fabric.helper_tag }}"
    helper_tag: "{{ fabric.helper_tag | default(fabric.helper_tag) }}"

- name: Set the version to 1.1.0 if the tag is a commit hashcode
  set_fact:
    project_version: >-
      {{ fabric.helper_tag | match(project_version) |
         ternary('1.1.0', project_version) }}
