- name: Install apt-transport-https if necessary.
  apt:
    name: apt-transport-https
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present
  register: add_repository_key
  ignore_errors: true

- name: Add Docker repository.
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Install latest git if necessary.
  apt:
    name: git
    state: latest

- name: Install packages
  apt:
    name: "{{ item }}"
  with_items:
    - ['docker-ce', 'python-dev', 'python-pip', 'libtool', 'libltdl-dev']
    - ['net-tools', 'netcat-openbsd', 'autoconf', 'automake']
    - ['make', 'g++', 'unzip', 'build-essential']

