---
- name: Setup variables
  set_fact:
    fabricworkdir: "/opt/gopath/{{ env }}/fabric"
    peerls: "{{ [] }}"
    cals: "{{ [] }}"
    ordererls: "{{ [] }}"
    peers: "{{ [] }}"
    peerorgs: "{{ [] }}"
    adminkeys: "{{ {} }}"
    allpeers: "{{ [] }}"
    allcas: "{{ [] }}"
    allorderers: "{{ [] }}"
    localhome: "/home/{{ fabric.ssh_user }}/.composer"
    network: "{{ fabric.bna_name | default('') }}"
  tags: [bnasetup, startupplayground]

- name: Get peer container list
  set_fact:
    peers: |
      {{ peers + [{'org':item.split('@')[1].split('.')[-1],
        'name':item.split('@')[1],
        'role':item.split('@')[0]}] }}
  with_items: "{{ fabric.network[hostvars[inventory_hostname].inter_name].peers | default([]) }}"
  tags: "bnasetup"

- name:
  set_fact:
    peerls: "{{ peerls | default([]) + item.value.peers | default([]) }}"
    cals: "{{ cals | default([]) + item.value.cas | default([]) }}"
    ordererls: "{{ ordererls | default([]) + item.value.orderers | default([]) }}"
  with_dict: "{{ fabric.network }}"

- name: Get all peer object list
  set_fact:
    allpeers: |
      {{ allpeers | default([]) + [{'org':item.split('@')[1].split('.')[-1],
        'name':item.split('@')[1],
        'role':item.split('@')[0]}] }}
  with_items: "{{ peerls }}"

- name: Get all ca object list
  set_fact:
    allcas: |
      {{ allcas | default([]) + [{ 'org':item.split('.')[-1],
        'name':item }] }}
  with_items: "{{ cals }}"

- set_fact:
    allorderers: |
      {{ allorderers | default([]) + [{ 'org':item.split('.')[-1],
        'name':item }] }}
  with_items: "{{ ordererls }}"

- name: Get the peer org list
  set_fact:
    peerorgs: "{{ peers | map(attribute='org') | list  | unique | sort }}"
  tags: "bnasetup"

- name: Make sure that working directory exists
  file:
    path: "{{ localhome }}"
    state: "directory"

- name: Pull composer container images from the docker hub
  command: "docker pull {{ fabric.repo.url }}{{ item }}"
  with_items:
    - "composer-cli:{{ fabric.composer_tag }}"
    - "composer-playground:{{ fabric.composer_tag }}"
  tags: "pullcomposerimages"

# - name: Check if PeerAdmin card is already imported
#   stat:
#     path: "{{ localhome }}/cards/PeerAdmin@{{ env }}-{{ peerorgs[0] }}"
#   register: peeradmin

- name: Create run/composer directory
  file:
    path: "{{ fabricworkdir }}/run/composer"
    state: "directory"

# - include_tasks: setup-Debian.yml
#   when: ansible_os_family == 'Debian'

# - include_tasks: setup-RedHat.yml
#   when: ansible_os_family == 'RedHat'

- name: Set node source
  shell: |
    curl https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  args:
    warn: no

- name: Install node
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
  shell: |
    . "$NVM_DIR/nvm.sh"
    . "$NVM_DIR/bash_completion"
    nvm install {{ fabric.nodejs_version }}
    nvm use {{ fabric.nodejs_version }}
  args:
    executable: /bin/bash
  no_log: true

- name: Create /run/composer directory
  file:
    path: "{{ fabricworkdir }}/run/composer"
    state: "directory"    

- name: Install composer npm packages globally.
  environment:
    NVM_DIR: "{{ ansible_env.HOME }}/.nvm"
    PATH: "{{ ansible_env.HOME }}/.nvm/versions/node/v{{ fabric.nodejs_version }}/bin:{{ ansible_env.PATH }}"
  npm:
    name: "{{ item }}"
    version: "{{ fabric.composer_tag }}"
    global: yes
  with_items:
    - composer-cli
    - composer-rest-server
    - composer-playground
#    - generator-hyperledger-composer

# - name: Install "yo" node.js package globally.
#   environment:
#     PATH: /home/{{ fabric.ssh_user }}/.nvm/versions/node/v8.9.4/bin:{{ ansible_env.PATH }}
#   npm:
#     name: yo
#     version: '2.0.1'
#     global: yes

- name:
  template:
    src: "{{ playbook_dir }}/composersetup/templates/endorsement-policy.json"
    dest: "{{ fabricworkdir }}/run/composer/"

- name: Process admin key files
  find:
    paths: "{{ fabricworkdir }}/run/keyfiles/orgs/{{ item }}/admin/msp/keystore"
    patterns: "*_sk"
    recurse: yes
  with_items:
    - "{{ peerorgs }}"
  register: adminprocesskeys

- name: Setup admin private key values
  set_fact:
    adminkeys: |
      {{ adminkeys | combine( {item.item: item.files[0].path.split('/')[-1] } ) }}
  with_items: "{{ adminprocesskeys.results }}"
  no_log: True

- name: Template connection profiles
  vars:
    clientorg: "{{ item }}"
    keyfilesdir: "{{ fabricworkdir }}/run/keyfiles"
  template:
    src: "{{ playbook_dir }}/fabricsetup/templates/network-config.j2"
    dest: "{{ fabricworkdir }}/run/composer/connection-{{ item }}.yml"
  with_items: "{{ peerorgs }}"

- name: Composer create card
  shell: 
    composer card create 
      -p ./connection-{{ item }}.yml 
      -u PeerAdmin 
      -c ../keyfiles/orgs/{{ item }}/admin/msp/signcerts/cert.pem
      -k ../keyfiles/orgs/{{ item }}/admin/msp/keystore/{{ adminkeys[item] }}
      -r PeerAdmin
      -r ChannelAdmin
      -f PeerAdmin@{{ env }}-{{ item }}.card
  args:
    chdir: "{{ fabricworkdir }}/run/composer/"
  with_items: "{{ peerorgs }}"

- name: Composer card import
  vars:
    DEBUG: "composer:*"
  shell: 
    composer card import -f PeerAdmin@{{ env }}-{{ item }}.card -c PeerAdmin@{{ env }}-{{ item }}
  args:
    chdir: "{{ fabricworkdir }}/run/composer/"
  with_items: "{{ peerorgs }}"

################################

- include_tasks: bnasetup.yml
  when: network | length > 0
  tags: "bnasetup"

# - name: Start composer playground
#   command: >-
#     docker run -v {{ localhome }}:/home/composer/.composer
#     -v {{ fabricworkdir }}:{{ fabricworkdir }}
#     --name composer-playground --publish 8080:8080
#     --detach hyperledger/composer-playground:{{ fabric.composer_tag }}
#     --dns-search fabricnet
#   tags: "startupplayground"

