---
- name: Setup variables
  set_fact:
    fabricworkdir: "/opt/gopath/{{ env }}/fabric"
    peerls: "{{ [] }}"
    cals: "{{ [] }}"
    ordererls: "{{ [] }}"
    peers: "{{ [] }}"
    peerorgs: "{{ [] }}"
    adminkeys: "{{ {} }}"
    allpeers: "{{ [] }}"
    allcas: "{{ [] }}"
    allorderers: "{{ [] }}"

- name: Get peer container list
  set_fact:
    peers: |
      {{ peers + [{'org':item.split('@')[1].split('.')[-1],
        'name':item.split('@')[1],
        'role':item.split('@')[0]}] }}
  with_items: "{{ fabric.network[hostvars[inventory_hostname].inter_name].peers | default([]) }}"

- name:
  set_fact:
    peerls: "{{ peerls | default([]) + item.value.peers | default([]) }}"
    cals: "{{ cals | default([]) + item.value.cas | default([]) }}"
    ordererls: "{{ ordererls | default([]) + item.value.orderers | default([]) }}"
  with_dict: "{{ fabric.network }}"

- name: Get all peer object list
  set_fact:
    allpeers: |
      {{ allpeers | default([]) + [{'org':item.split('@')[1].split('.')[-1],
        'name':item.split('@')[1],
        'role':item.split('@')[0]}] }}
  with_items: "{{ peerls }}"

- name: Get all ca object list
  set_fact:
    allcas: |
      {{ allcas | default([]) + [{ 'org':item.split('.')[-1],
        'name':item }] }}
  with_items: "{{ cals }}"

- set_fact:
    allorderers: |
      {{ allorderers | default([]) + [{ 'org':item.split('.')[-1],
        'name':item }] }}
  with_items: "{{ ordererls }}"

- name: Get the peer org list
  set_fact:
    peerorgs: "{{ peers | map(attribute='org') | list  | unique | sort }}"

- name: Create run/composer directory
  file:
    path: "{{ fabricworkdir }}/run/composer"
    state: "directory"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Download nvm install.sh
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh
    dest: "{{ fabricworkdir }}/run/composer/install.sh"
    mode: 0744

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Set node source
  shell: |
    curl https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
  args:
    warn: no

- name: Install node
  environment:
    NVM_DIR: /home/{{ fabric.ssh_user }}/.nvm
  shell: |
    . "$NVM_DIR/nvm.sh"
    . "$NVM_DIR/bash_completion"
    nvm install 8.9.4
    nvm use 8.9.4
  args:
    executable: /bin/bash
  no_log: true

- name: Create /run/composer directory
  file:
    path: "{{ fabricworkdir }}/run/composer"
    state: "directory"    

- name: Install composer npm packages globally.
  environment:
    NVM_DIR: ~/.nvm
    PATH: ~/.nvm/versions/node/v8.9.4/bin:{{ ansible_env.PATH }}
  npm:
    name: "{{ item }}"
    version: "{{ fabric.composer_tag }}"
    global: yes
  with_items:
    - composer-cli
    - generator-hyperledger-composer
    - composer-rest-server

# - name: Install composer npm packages globally.
#   npm:
#     name: composer-rest-server
#     version: '0.16.1'
#     global: yes

- name: Install "yo" node.js package globally.
  environment:
    PATH: /home/{{ fabric.ssh_user }}/.nvm/versions/node/v8.9.4/bin:{{ ansible_env.PATH }}
  npm:
    name: yo
    version: '2.0.0'
    global: yes

# - name: Template composer Org only connection profiles
#   vars:
#     ORG_ONLY: true
#   template:
#     src: "{{ playbook_dir }}/composersetup/templates/composer-connection.j2"
#     dest: "{{ fabricworkdir }}/run/composer/connection-{{ item }}-only.json"
#   with_items: "{{ peerorgs }}"

# - name: Template composer Org connection profiles
#   vars:
#     ORG_ONLY: false
#   template:
#     src: "{{ playbook_dir }}/composersetup/templates/composer-connection.j2"
#     dest: "{{ fabricworkdir }}/run/composer/connection-{{ item }}.json"
#   with_items: "{{ peerorgs }}"

- name: Process admin key files
  find:
    paths: "{{ fabricworkdir }}/run/keyfiles/{{ item.org }}/users/Admin@{{ item.org }}/msp/keystore"
    patterns: "*_sk"
    recurse: yes
  with_items:
    - "{{ allcas }}"
  register: adminprocesskeys

- name: Setup admin private key values
  set_fact:
    adminkeys: |
      {{ adminkeys | combine( {item.item.org: item.files[0].path.split('/')[-1] } ) }}
  with_items: "{{ adminprocesskeys.results }}"
  no_log: True

- name: Template connection profiles
  vars:
    clientorg: "{{ item }}"
    keyfilesdir: "{{ fabricworkdir }}/run/keyfiles"
  template:
    src: "{{ playbook_dir }}/fabricsetup/templates/network-config.j2"
    dest: "{{ fabricworkdir }}/run/composer/connection-{{ item }}.yml"
  with_items: "{{ peerorgs }}"

- name: Composer create card
  shell: 
    composer card create 
      -p ./connection-{{ item }}.yml 
      -u PeerAdmin 
      -c ../keyfiles/{{ item }}/users/Admin@{{ item }}/msp/signcerts/Admin@{{ item }}-cert.pem
      -k ../keyfiles/{{ item }}/users/Admin@{{ item }}/msp/keystore/{{ adminkeys[item] }}
      -r PeerAdmin
      -r ChannelAdmin
      -f PeerAdmin@{{ env }}-{{ item }}.card
  args:
    chdir: "{{ fabricworkdir }}/run/composer/"
  with_items: "{{ peerorgs }}"

- name: Composer card import
  vars:
    DEBUG: "composer:*"
  shell: 
    composer card import -f PeerAdmin@{{ env }}-{{ item }}.card -n PeerAdmin@{{ env }}-{{ item }}
  args:
    chdir: "{{ fabricworkdir }}/run/composer/"
  with_items: "{{ peerorgs }}"

- name: Composer runtime install
  vars:
    DEBUG: "composer:*"
  shell: 
    composer runtime install -c PeerAdmin@{{ env }}-{{ item }} -n test-network
  args:
    chdir: "{{ fabricworkdir }}/run/composer/"
  with_items: "{{ peerorgs }}"

# - name: Composer create identities
#   vars:
#     DEBUG: "composer:*"
#   shell:
#     composer identity request 
#       -c PeerAdmin@{{ env }}-org1
#       -u admin -s adminpw 
#       -d alice
#   args:
#     chdir: "{{ fabricworkdir }}/run/composer/"

- name: Composer create identities
  vars:
    DEBUG: "composer:*"
  shell:
    composer identity request 
      -c PeerAdmin@{{ env }}-{{ item }}
      -u admin -s adminpw 
      -d user-{{ item }}
  args:
    chdir: "{{ fabricworkdir }}/run/composer/"
  with_items: "{{ peerorgs }}"

- name: Copy empty-network .bna folder
  copy:
    src: "{{ playbook_dir }}/composersetup/files/test-network@0.0.1.bna"
    dest: "{{ fabricworkdir }}/run/composer/"

- name: Composer network start
  vars:
    DEBUG: "composer:*"
  shell:
    composer network start 
      --card PeerAdmin@{{ env }}-{{ peerorgs.0 }}
      --archiveFile test-network@0.0.1.bna
      --networkAdmin user-{{ peerorgs.0 }}
      --networkAdminCertificateFile user-{{ peerorgs.0 }}/admin-pub.pem
      #--networkAdmin bob
      #--networkAdminEnrollSecret bob/admin-pub.pem
  args:
    chdir: "{{ fabricworkdir }}/run/composer/"

- name: Composer create Alice's card
  vars:
    DEBUG: "composer:*"
    user: user-{{ item }}
  shell:
    composer card create 
      -p connection-{{ item }}.yml 
      -u {{ user }} 
      -n test-network 
      -c {{ user }}/admin-pub.pem 
      -k {{ user }}/admin-priv.pem
  args:
    chdir: "{{ fabricworkdir }}/run/composer/"
  with_items: "{{ peerorgs }}"

- name: Composer Alice's card import
  vars:
    DEBUG: "composer:*"
  shell:
    composer card import -f user-{{ item }}@test-network.card
  args:
    chdir: "{{ fabricworkdir }}/run/composer/"
  with_items: "{{ peerorgs }}"

