---


  # args:
  #   warn: no

# - name: Set node source
#   shell: |
#     nvm install 8
#   args:
#     warn: no

# - name: Set node source
#   shell: nvm use 8
#   args:
#     executable: /bin/bash


# - name: Unarchive nodejs
#   unarchive:
#     src: http://nodejs.org/dist/v{{ fabric.nodejs_version }}/node-v{{ fabric.nodejs_version }}-linux-x64.tar.gz #TODO
#     dest: /usr/local
#     remote_src: yes

# - name: Set node source
#   become: true
#   shell: curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash -
#   args:
#     warn: no

# - name: Install nodejs
#   yum:
#     name: nodejs
#     state: present

# - name: Add Nodesource apt key.
#   apt_key:
#     url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
#     id: "68576280"
#     state: present

# - name: Add NodeSource repositories for Node.js.
#   apt_repository:
#     repo: "{{ item }}"
#     state: present
#   with_items:
#     - "deb https://deb.nodesource.com/node_{{ fabric.nodejs_version }} {{ ansible_distribution_release }} main"
#     - "deb-src https://deb.nodesource.com/node_{{ fabric.nodejs_version }} {{ ansible_distribution_release }} main"
#   register: node_repo

# - name: Update apt cache if repo was added.
#   apt: update_cache=yes
#   when: node_repo.changed

# - name: Ensure Node.js and npm are installed.
#   apt: "name=nodejs={{ fabric.nodejs_version|regex_replace('x', '') }}* state=present"

# - name: Update repository cache and install libssl-dev
#   become: true
#   yum:
#     name: libssl-dev
#     update_cache: yes