---
# The url to the fabric source repository
GIT_URL: "http://gerrit.hyperledger.org/r/fabric"

# The gerrit patch set reference, should be automatically set by gerrit
#GERRIT_REFSPEC: "refs/changes/13/13113/1" # 1.0.2
#GERRIT_REFSPEC: "refs/tags/v1.0.4" # 1.0.4
#GERRIT_REFSPEC: '' # Head
GERRIT_REFSPEC: "refs/tags/v1.1.0-preview"

# This variable defines fabric network attributes
fabric: {

  # The user to connect to the server
  ssh_user: "blockchain",

  # options are "goleveldb", "CouchDB", default is goleveldb
  peer_db: "CouchDB",
  tls: true,

  # The following section defines how the fabric network is going to be made up
  # cas indicates certificate authority containers
  # peers indicates peer containers
  # orderers indicates orderer containers
  # kafka indicates kafka containers
  # all names must be in lower case. Numeric characters cannot be used to start
  # or end a name. Character dot (.) can only be used in names of peers and orderers.

  channel_name: businesschannel,

  network: {
    fabric001: {
      cas: ["ca1.org1", "ca1.ordererorg1"],
      peers: ["anchor@peer1.org1", "anchor@peer1.org2"],
      orderers: ["orderer1.ordererorg1"],
      zookeepers: ["zookeeper1"],
      kafkas: ["kafka1"],
      servers: ["server1"]
    },
    fabric002: {
      cas: ["ca1.org2"],
      peers: ["worker@peer2.org1", "worker@peer2.org2"],
      orderers: ["orderer2.ordererorg1"],
      zookeepers: ["zookeeper2", "zookeeper3"],
      kafkas: ["kafka2"]
    },
    fabric003: {
      cas: ["ca1.ordererorg2"],
      peers: ["worker@peer3.org1", "worker@peer3.org2"],
      orderers: ["orderer1.ordererorg2"],
      zookeepers: ["zookeeper4"],
      kafkas: ["kafka3"]
    }
  },

  tag: "1.1.0-preview",
  baseimage_tag: "0.4.2",
  ca: { tag: "1.1.0-preview", admin: "admin", adminpw: "adminpw" },

  # Composer settings
  composer_tag: "0.16.1",
  nodejs_version: "8.9.3"
}
