---
# The url to the fabric source repository
FABRIC_GIT_URL: "http://gerrit.hyperledger.org/r/fabric"
FABRIC_CA_GIT_URL: "http://gerrit.hyperledger.org/r/fabric-ca"

# The gerrit patch set reference, should be automatically set by gerrit
#GERRIT_REFSPEC: "refs/tags/v1.0.5" # 1.0.5
#GERRIT_REFSPEC: '' # Head
GERRIT_REFSPEC: "refs/tags/v1.1.0-rc1"

# This variable defines fabric network attributes
fabric: {

  # The user to connect to the server
  ssh_user: "blockchain",

  # options are "goleveldb", "CouchDB", default is goleveldb
  peer_db: "CouchDB",
  tls: true,
  logging_level: "DEBUG",

  # The following section defines how the fabric network is going to be made up
  # cas indicates certificate authority containers
  # peers indicates peer containers
  # orderers indicates orderer containers
  # kafka indicates kafka containers
  # all names must be in lower case. Numeric characters cannot be used to start
  # or end a name. Character dot (.) can only be used in names of peers and orderers.

  channel_name: businesschannel,

  network: {
    fabric001: {
      cas: ["ca1.org1", "ca1.ordererorg1"],
      peers: ["anchor@peer1.org1", "anchor@peer1.org2"],
      orderers: ["orderer1.ordererorg1"],
      zookeepers: ["zookeeper1"],
      kafkas: ["kafka1"],
      server: "server1"
    },
    fabric002: {
      cas: ["ca1.org2"],
      peers: ["worker@peer2.org1", "worker@peer2.org2"],
      orderers: ["orderer2.ordererorg1"],
      zookeepers: ["zookeeper2"],
      kafkas: ["kafka2", "kafka3"]
    },
    fabric003: {
      cas: ["ca1.ordererorg2"],
      peers: ["worker@peer3.org1", "worker@peer3.org2"],
      orderers: ["orderer1.ordererorg2"],
      zookeepers: ["zookeeper3"],
      kafkas: ["kafka4"]
    }
  },

  baseimage_tag: "1.1.0",
  helper_tag: "0.4.7",

  # Composer settings
  composer_tag: "0.19.1",
  nodejs_version: "8.11.1",

  repo: {
    # the url defines docker hub project access point
    # official hub - url: "hyperledger/",
    # fabric build hub - url: "nexus3.hyperledger.org:10001/hyperledger/",
    url: "hyperledger/",
    #username: "",
    #password: "",

    # locations to download fabric binaries. This url should point to a
    # compressed such as tar or zip file which contains necessary binaries
    # such as configtxgen, configtxlator, cryptogen etc.
    bin: ""
  }
}
