---
# This variable defines cloud provision attributes
cluster: {
  ssh_user: "blockchain",
  public_key_file: "/home/simon/.ssh/id_rsa.pub",
  private_key_file: "/home/simon/.ssh/id_rsa",
  # This variable indicate what IP should be used, only valid values are
  # private_ip or public_ip
  node_ip: "public_ip",
  #assign_public_ip: true,

  container_network: {
    Network: "10.1.0.0/16",
    SubnetLen: 24,
    SubnetMin: "10.1.0.0",
    SubnetMax: "10.1.255.0",
    Backend: {
      Type: "udp",
      Port: 8285
    }
  },

  # the section defines preallocated IP addresses for each node, if there is no
  # preallocated IPs, leave it blank
  #node_ips: ["172.16.67.237", "172.16.67. 246", "172.16.67.247"],
  node_ips: [],  

  # fabric network node name
  domain: "fabricnet",

  etcdnodes: ["fabric001", "fabric002", "fabric003"],
  builders: ["fabric001"],

  flannel_repo: "https://github.com/coreos/flannel/releases/download/v0.7.1/flannel-v0.7.1-linux-amd64.tar.gz",
  etcd_repo: "https://github.com/coreos/etcd/releases/download/v3.2.0/etcd-v3.2.0-linux-amd64.tar.gz",
  k8s_repo: "https://storage.googleapis.com/kubernetes-release/release/v1.9.1/bin/linux/amd64/",
  go_repo: "https://dl.google.com/go/go1.9.2.linux-amd64.tar.gz",

  go_ver: "1.10"
}
